# Generated by Django 3.1.2 on 2020-10-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('symbol', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('latest_trade', models.DateTimeField()),
                ('bid', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
            ],
        ),
    ]
