# Generated by Django 3.1.2 on 2020-10-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='currency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
            preserve_default=False,
        ),
    ]
